# submit a job node for QC steps (trim adapter/low quality reads + filter low quality reads)

### this is a single job that stages large data
# Files for the below lines MUST all be somewhere within /home/username,
# and not within /staging/username

initialdir = $(outdir_home)/$(job)
executable = $(dir_scripts)/01qc.sh
arguments = "$(sequencing_run) $(read1) $(read2) $(outdir_staging) $(indir_staging) $(job) $(conda_pack_squid)"
log = $(job).log
output = $(job).out
error = $(job).err
when_to_transfer_output = ON_EXIT_OR_EVICT

## Do NOT list the large data files here
transfer_input_files = $(software_pack), $(conda_pack_squid)
should_transfer_files = YES

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

# Make sure to still include lines like "request_memory", "request_disk", "request_cpus", etc. 
+WantFlocking = false
+WantGlideIn = false
request_cpus = $(request_cpus)
request_disk = $(request_disk)
request_memory = $(request_memory)
queue