# submit a job node for SNP Calling & filtering

### this is a single job that stages large data
# Files for the below lines MUST all be somewhere within /home/username,
# and not within /staging/username

initialdir = $(outdir_home)/$(job)
executable = $(dir_scripts)/07callsnp.sh
arguments = "$(outdir_staging) $(conda_pack_squid) $(genome_seq_squid) $(job_parent) $(job)"
log = $(job).log
output = $(job).out
error = $(job).err
when_to_transfer_output = ON_EXIT_OR_EVICT

## Do NOT list the large data files here
transfer_input_files = $(conda_pack_squid), $(genome_seq_squid), $(software_pack), $(bam_list)
should_transfer_files = YES

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

# Make sure to still include lines like "request_memory", "request_disk", "request_cpus", etc. 
+WantFlocking = false
+WantGlideIn = false
request_cpus = $(request_cpus)
request_disk = $(request_disk)
request_memory = $(request_memory)
queue